name: CI/CD - Kitchen Service

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]


jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Get source code
      - name: Checkout source
        uses: actions/checkout@v4

      # Install Java + Maven cache
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      #  Build & test
      - name: Build & Test
        run: |
          cd kitchen-service
          mvn clean verify

      # Authenticate GitHub â†’ Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build & push Docker image
      - name: Build container image
        run: |
          gcloud builds submit kitchen-service \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/kitchen-service

      #  Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy kitchen-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/kitchen-service \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
