name: CI/CD - Order Service

on:
  push:
    paths:
      - 'order-service/**'
  pull_request:
    paths:
      - 'order-service/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Get source code
      - name: Checkout source
        uses: actions/checkout@v4

      # Install Java + Maven cache
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      #  Build & test
      - name: Build & Test
        run: |
          cd order-service
          mvn clean verify

      # Authenticate GitHub â†’ Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify gcloud project
        run: gcloud config get-value project
      # Build & push Docker image
      - name: Build container image
        run: |
          gcloud builds submit order-service \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/order-service

      #  Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy order-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/order-service \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
